version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=movie
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'